### ISSUE TITLE
Error building TDI

### ISSUE THREAD

**Issue by Dscano** [p4lang/tdi#84]
Hi,

I'm trying to build TDI but i get this error,  do you have any clue to solve it?
![Screenshot from 2022-08-08 17-56-04](https://user-images.githubusercontent.com/25779169/183461061-9dd7e6e6-f279-4a7a-801f-4cba7693cac9.png)

**Comment by weiqiand** [comment]
Look like your environment missing the expat lib.
1. for fedora, dnf install expat-devel.
2. for ubuntu, apt-get instal libexpat1-dev.

or run the python tools/setup/install_dep.py for all the missing packages in your build machine.
Regards,
Weiqian

**Comment by Dscano** [comment]
Thank you so muck, it works!
